import type { ReservaDto, ViagemDto } from "@/api/viagens";

/** Viagem do protótipo (`07-viagem`): Carlos Mendes · Lisboa, duas reservas, resumo e repasse. */
export const RESERVA_1: ReservaDto = {
  id: "r1",
  versao: "1",
  fornecedorId: "f1",
  fornecedorNome: "CVC Operadora",
  localizador: "K7X2PQ",
  dataCompra: "2026-02-10",
  status: "pendente",
  tiposServico: ["aereo", "hospedagem", "passeio"],
  formasPagamento: ["pix"],
  ravClienteModo: "retido_agencia",
  fluxoPagamento: "cliente_paga_agencia",
  nfseStatus: "falta_emitir",
  observacoes: null,
  dataPrevistaComissao: "2026-05-10",
  valorTotal: 10_000,
  valorTaxas: 0,
  valorComissao: 1000,
  ravOperadora: 0,
  valorCliente: 10_500,
  taxaServico: 500,
  ravCliente: 0,
  valorEsperadoOperadora: 1000,
  receitaPrevista: 1500,
  percentualComissao: 10,
  comissaoMantida: false,
  canceladaEm: null,
  motivoCancelamento: null,
  desfechoCancelamento: null,
  nfseTomador: null,
  nfseNumero: null,
  nfseDataEmissao: null,
  conciliacaoEncerrada: false,
  situacaoComissao: "a_receber",
};

export const RESERVA_2: ReservaDto = {
  ...RESERVA_1,
  id: "r2",
  fornecedorId: "f2",
  fornecedorNome: "Decolar",
  localizador: "DCL-88213",
  status: "emitida",
  tiposServico: ["seguro", "traslado"],
  valorTotal: 3000,
  valorComissao: 300,
  valorCliente: 3200,
  taxaServico: 200,
  valorEsperadoOperadora: 300,
  receitaPrevista: 500,
};

export const VIAGEM: ViagemDto = {
  id: "v1",
  codigo: "VG-2026-0042",
  versao: "42",
  destino: "Lisboa",
  tipo: "internacional",
  dataIda: "2026-04-18",
  dataVolta: "2026-04-28",
  vendedorId: "u2",
  vendedorNome: "Ana Paula",
  agenteId: "u1",
  agenteNome: "Guilherme",
  ocasiao: null,
  observacoes: null,
  cancelada: false,
  canceladaEm: null,
  motivoCancelamento: null,
  faseOperacional: "em_emissao",
  faseFinanceira: "a_receber",
  passageiros: [
    { clienteId: "c1", nome: "Carlos Mendes", titular: true },
    { clienteId: "c2", nome: "Lúcia Mendes", titular: false },
  ],
  reservas: [RESERVA_1, RESERVA_2],
  repasse: { id: "rp1", valor: 300, status: "bloqueado" },
  resumo: {
    vendaTotal: 13_700,
    custoFornecedores: 13_000,
    receitaPrevista: 2000,
    receitaRecebida: 0,
    repasseValor: 300,
    repasseStatus: "bloqueado",
    despesasViagem: 180,
    resultado: 1640,
  },
};
